version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_web
    ports:
      - "8000:80"
      - "5173:5173"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_laravel_demo
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
